---
engine_version: 0.2.1
file_version: 2021-09-16 11:09:45.185275000 Z
resources:
- name: access_token
  preferences:
    columns:
    - column_type: reference
      default_value: ''
      reference:
        name: owner
        display_name: Owner
        model_name:
        reference_type: belongs_to
        foreign_key: owner_id
        primary_key: id
        options: {}
        polymorphic: true
        virtual: true
      name: owner_id
  updated_at: 2021-08-09 18:10:14.389984000 +00:00
- name: account_user
  preferences:
    columns:
    - column_type: reference
      default_value: ''
      reference:
        name: inviter
        display_name: Inviter
        model_name: user
        reference_type: belongs_to
        foreign_key: inviter_id
        primary_key: id
        options: {}
        polymorphic: false
        virtual: true
      name: inviter_id
  updated_at: 2021-08-10 08:52:18.355126000 +00:00
- name: action_text_rich_text
  preferences:
    visible: false
  updated_at: 2021-08-24 16:02:15.005295000 +00:00
- name: active_storage/attachment
  preferences:
    columns:
    - access_type: read_write
      name: path
    visible: false
  updated_at: 2021-08-24 16:04:31.827403000 +00:00
- name: blacklisted_email
  preferences:
    columns:
    - column_type: tag
      default_value: ''
      format:
        select_options:
        - unsubscribe
        - asd
      name: reason
  updated_at: 2021-08-11 16:28:46.183143000 +00:00
- name: campaign
  preferences:
    columns:
    - column_type: richtext
      default_value: ''
      name: body
  updated_at: 2021-08-06 10:12:50.916720000 +00:00
- name: comment
  preferences:
    columns:
    - column_type: textarea
      default_value: ''
      name: body_markdown
  updated_at: 2021-08-09 17:57:01.830027000 +00:00
- name: customer
  preferences:
    columns:
    - column_type: tag
      default_value: ''
      format:
        select_options:
        - standard
        - vip
      name: kind
    - column_type: percentage
      default_value: ''
      name: reputation
    - column_type: reference
      default_value: ''
      reference:
        name: country
        display_name: Country code
        model_name: country
        reference_type: belongs_to
        foreign_key: country_code
        primary_key: code
        options: {}
        polymorphic: false
        virtual: true
      display_name: Country
      name: country_code
  updated_at: 2021-08-24 15:58:31.052654000 +00:00
- name: inbox
  preferences:
    columns:
    - default_value: ''
      name: channel_id
  updated_at: 2021-08-10 10:10:48.976474000 +00:00
- name: line_item
  preferences:
    columns:
    - column_type: currency
      default_value: ''
      format:
        currency: USD
        currency_base: cents
      name: unit_price
    - column_type: reference
      default_value: ''
      reference:
        name: product
        display_name: Product
        model_name: product
        reference_type: belongs_to
        foreign_key: product_id
        primary_key: id
        options: {}
        polymorphic: false
        virtual: true
      name: product_id
  updated_at: 2021-08-06 07:35:51.306733000 +00:00
- name: list
  preferences:
    columns:
    - column_type: tag
      default_value: ''
      name: tags
    custom_sql: 'SELECT ls.*, lsl.status FROM lists as ls JOIN subscriber_lists as
      lsl ON lsl.list_id = ls.id '
  updated_at: 2021-08-09 13:53:47.865929000 +00:00
- name: note
  preferences:
    columns:
    - default_value: ''
      column_type: reference
      reference:
        name: record
        display_name: Record
        model_name:
        reference_type: belongs_to
        foreign_key: record_id
        primary_key: id
        options: {}
        polymorphic: true
        virtual: true
      name: record_id
  updated_at: 2021-08-06 07:06:20.129434000 +00:00
- name: order
  preferences:
    columns:
    - default_value: ''
      reference:
        name: customer
        display_name: Customer
        model_name: customer
        reference_type: belongs_to
        foreign_key: customer_id
        primary_key: id
        options: {}
        polymorphic: false
        virtual: true
      name: customer_id
    - column_type: tag
      default_value: ''
      name: status
  updated_at: 2021-08-06 06:53:58.347881000 +00:00
- name: product
  preferences:
    columns:
    - column_type: textarea
      default_value: ''
      name: description
    - format:
        currency: USD
        currency_base: cents
      name: price
  updated_at: 2021-08-24 16:01:53.174972000 +00:00
- name: subscriber
  preferences:
    associations:
    - visible: false
      name: subscriber_lists
  updated_at: 2021-08-09 13:54:30.247445000 +00:00
- name: super_admin
  preferences:
    columns:
    - access_type: hidden
      name: encrypted_password
  updated_at: 2021-08-09 18:11:58.726566000 +00:00
- name: user
  preferences:
    columns:
    - column_type: tag
      default_value: ''
      name: groups
    - access_type: hidden
      name: encrypted_password
    - access_type: hidden
      name: reset_password_token
  updated_at: 2021-08-06 06:19:09.676790000 +00:00
configs:
- key: header.links
  value:
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin
  updated_at: 2021-08-24 15:14:28.144612000 +00:00
- key: language
  value: en
  updated_at: 2021-09-16 11:09:45.185275000 +00:00
- key: resources.access_token.columns.order
  value:
  - id
  - owner_id
  - owner_type
  - token
  - updated_at
  - created_at
  updated_at: 2021-08-09 18:10:25.443425000 +00:00
- key: resources.customer.columns.order
  value:
  - id
  - name
  - email
  - email_subscriber
  - country_code
  - kind
  - reputation
  - updated_at
  - created_at
  updated_at: 2021-08-06 08:12:53.725847000 +00:00
queries: []
dashboards: []
forms: []
alerts: []
